# Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By
# starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms
# in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def sumEvenFibonacci(max):
    fib_prev = 1
    fib_next = 2
    total = 0
    while(fib_next<max):
        if(fib_next%2 == 0):
            total+=fib_next

        temp = fib_next
        fib_next += fib_prev
        fib_prev = temp

    return total


def main():
    max = 4000000
    print(sumEvenFibonacci(max))


if __name__ == "__main__":
    main()